# Copyright Scoir Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

coverage:
  status:
    project:
      default:
        target: 0% #yup
    patch:
      default:
        target: 70%
        only_pulls: true
