###############################################################
#
#  HTTP Indy resolver configuration
#
###############################################################
resolver:
  method: sov
  http:
    host: 0.0.0.0
    port: 5544
