apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq
spec:
  ports:
  - port: {{.Values.rabbitmq.port}}
    protocol: TCP
    targetPort: {{.Values.rabbitmq.port}}
  sessionAffinity: None
  type: ClusterIP
