apiVersion: v1
kind: Service
metadata:
  name: {{ include "canis.fullname" . }}-didcomm-cloudagent
  labels:
    name: {{ include "canis.fullname" . }}-didcomm-cloudagent
spec:
  ports:
    - name: grpc
      port: {{ .Values.cloudagent.grpc.port }}
      protocol: TCP
      targetPort: {{ .Values.cloudagent.grpc.port }}
    - name: ws-didcomm
      port: {{ .Values.cloudagent.inbound.wsPort }}
      protocol: TCP
      targetPort: {{ .Values.cloudagent.inbound.wsPort }}
  selector:
    name: {{ include "canis.fullname" . }}-didcomm-cloudagent
  sessionAffinity: None
  type: ClusterIP
