apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canis.fullname" . }}-http-indy-resolver
  labels:
    name: {{ include "canis.fullname" . }}-http-indy-resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "canis.fullname" . }}-http-indy-resolver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ include "canis.fullname" . }}-http-indy-resolver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "canis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          name: http-indy-resolver
          command:
            - http-indy-resolver
            - start
          ports:
            - name: http
              containerPort: {{ .Values.httpIndyResolver.http.port }}
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: "/etc/canis"
              name: http-indy-resolver-config
            - mountPath: "/etc/canis/common"
              name: common-config
      restartPolicy: Always
      volumes:
        - name: http-indy-resolver-config
          configMap:
            name: {{ include "canis.fullname" . }}-http-indy-resolver-config
        - name: common-config
          configMap:
            name: {{ include "canis.fullname" . }}-common-config
