apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canis.fullname" . }}-http-indy-resolver-config
  labels:
    app: {{ include "canis.fullname" . }}-canis-http-indy-resolver
data:
  http-indy-resolver.yaml: |-
    ###############################################################
    #
    #  HTTP Indy resolver configuration
    #
    ###############################################################
    resolver:
      method: sov
      http:
        host: 0.0.0.0
        port: {{ .Values.httpIndyResolver.http.port }}
